server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # IMPORTANT: Define the location for your FastAPI API requests
    location /api/ {
        # The URL for the backend is the Docker Compose service name: 'backend'
        proxy_pass http://fastapi_backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}