FROM node:18-alpine AS base
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy app source
COPY . .

EXPOSE 3000

CMD ["node", "backend/index.js"]
