"""
JSON code export utility for storing generated code from agents.

Saves frontend, backend, and infra code to JSON format with metadata.
"""

import json
import os
from datetime import datetime
from typing import Dict, Any, Optional


class CodeExporter:
    """Export generated code to JSON format."""

    def __init__(self, output_dir: str = "output"):
        """
        Initialize the exporter.

        Args:
            output_dir: Directory to save JSON exports (default: output/)
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def export_to_json(
        self,
        frontend_files: Dict[str, str],
        backend_files: Dict[str, str],
        infra_files: Optional[Dict[str, str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        filename: Optional[str] = None,
    ) -> str:
        """
        Export generated code to a JSON file.

        Args:
            frontend_files: Dict of frontend filenames -> code content
            backend_files: Dict of backend filenames -> code content
            infra_files: Dict of infra filenames -> code content (optional)
            metadata: Additional metadata to include (e.g., user_story, architecture_plan)
            filename: Custom filename (default: timestamp-based)

        Returns:
            Path to the created JSON file
        """
        if infra_files is None:
            infra_files = {}

        # Generate filename if not provided
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"generated_code_{timestamp}.json"

        # Build the export structure
        export_data = {
            "timestamp": datetime.now().isoformat(),
            "metadata": metadata or {},
            "frontend": {
                "files": frontend_files,
                "count": len(frontend_files),
            },
            "backend": {
                "files": backend_files,
                "count": len(backend_files),
            },
            "infrastructure": {
                "files": infra_files,
                "count": len(infra_files),
            },
        }

        # Write to JSON file
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(export_data, f, indent=2, ensure_ascii=False)

        print(f"✅ Code exported to JSON: {filepath}")
        return filepath

    def export_by_agent(
        self,
        agent_name: str,
        files: Dict[str, str],
        metadata: Optional[Dict[str, Any]] = None,
        filename: Optional[str] = None,
    ) -> str:
        """
        Export code generated by a specific agent to JSON.

        Args:
            agent_name: Name of the agent (e.g., 'frontend', 'backend', 'architect')
            files: Dict of filenames -> code content
            metadata: Additional metadata
            filename: Custom filename

        Returns:
            Path to the created JSON file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{agent_name}_code_{timestamp}.json"

        export_data = {
            "agent": agent_name,
            "timestamp": datetime.now().isoformat(),
            "metadata": metadata or {},
            "files": files,
            "file_count": len(files),
        }

        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(export_data, f, indent=2, ensure_ascii=False)

        print(f"✅ {agent_name.upper()} code exported to JSON: {filepath}")
        return filepath

    def load_from_json(self, filepath: str) -> Dict[str, Any]:
        """
        Load previously exported code from a JSON file.

        Args:
            filepath: Path to the JSON file

        Returns:
            Dictionary containing the exported code and metadata
        """
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data

    def summary(self, frontend_files: Dict[str, str], backend_files: Dict[str, str]) -> str:
        """
        Generate a summary of files to be exported.

        Args:
            frontend_files: Frontend files dict
            backend_files: Backend files dict

        Returns:
            Summary string
        """
        summary_text = (
            f"\n📋 Code Export Summary:\n"
            f"   Frontend Files: {len(frontend_files)}\n"
            f"   Backend Files: {len(backend_files)}\n"
            f"   Total Files: {len(frontend_files) + len(backend_files)}\n"
        )
        return summary_text
